update logging and README

diff --git a/revpipe b/revpipe
--- a/revpipe
+++ b/revpipe
@@ -34,47 +34,78 @@ PUBLIC_DNS_SERVERS=( 208.67.222.220 8.8.8.8 156.154.70.1 198.153.192.1 4.2.2.1 )
 #-------------------------------------------------------------------------------
 #                        P R O G R A M   B E G I N S
 #-------------------------------------------------------------------------------
+# log setup
+LOG_ROOT=/var/log
 SCRIPT=${0##*/}
-LOG=/var/log/${SCRIPT}.log
-STDERR=/var/log/${SCRIPT}.stderr
-[[ "${SSH_DEBUG}" ]] && {
-    STDOUT=/var/log/${SCRIPT}.stdout
-} || {
-    STDOUT=/dev/null
-}
-export SCRIPT SSH_DEBUG LOG STDOUT STDERR
+mkdir -p ${LOG_ROOT}/${SCRIPT}
+LOG=${LOG_ROOT}/${SCRIPT}/${SCRIPT}.log
+STDOUT_LOG=${LOG_ROOT}/${SCRIPT}/${SCRIPT}.stdout
+STDERR_LOG=${LOG_ROOT}/${SCRIPT}/${SCRIPT}.stderr
+DEBUG_LOG=${LOG_ROOT}/${SCRIPT}/${SCRIPT}.debug
+ERROR_EMAIL=root
 
-[[ "$(id -u)" == 0 ]] || { echo "you must be root"; exit 1; }
-
-# logging methods
-log()
+function log()
 {
     # be transparent to return code
     local _rtn=${?}
     local _msg=
     local _log=
+    local _pre=
 
     case "${1}" in
-        "-err") _msg="$(cat -)"; _log=${STDERR} ;;
-        "-out") _msg="$(cat -)"; _log=${STDOUT} ;;
-        *) _msg="${*}"; _log=${LOG} ;;
+
+        "-err")
+            _msg="$(cat -)"; _pre="Error: "; _log=${STDERR_LOG:-~/${0##*/}.stderr}
+            [[ "${_msg}" ]] && {
+                echo "${_msg}" | mail -s"[${0##*/}] Error on ${HOSTNAME}" ${ERROR_EMAIL:-${USER}}
+            }
+            ;;
+
+        "-out")
+            _msg="$(cat -)"; _pre="Stdout: "; _log=${STDOUT_LOG:-~/${0##*/}.stdout}
+            ;;
+
+        "-dbg")
+            [[ ${DEBUG:-0} -eq 1 ]] && {
+                _msg="$(cat -)"; _pre="Debug: "; _log=${DEBUG_LOG:-~/${0##*/}.debug}
+            } || {
+                return ${_rtn}
+            }
+            ;;
+
+        *) _msg="${*}"; _log=${LOG:-~/${0##*/}.log} ;;
+
     esac
 
     while IFS= read line; do
         [[ "${line}" ]] && {
-            echo "$(date) ${SCRIPT}: ${line}" >>${_log}
+            echo "$(date +"%b %e %H:%M:%S") ${SCRIPT:-${0##*/}}: ${_pre}${line}" >>${_log}
         }
     done < <(echo "${_msg}")
 
     return ${_rtn}
 }
+#
+function error()
+{
+    echo -e "${*}" > >(log -err)
+}
+#
+function debug()
+{
+    echo -e "${*}" > >(log -dbg)
+}
+# push all stderr from any failure to the error log
+exec 2> >(log -err)
+#-------------------------------------------------------------------------------
+
+[[ "$(id -u)" == 0 ]] || { echo "you must be root"; exit 1; }
 
 [[ $(which dig) ]] || {
-    log "this program requires 'dig' to function. Please install it"
-    echo "dig is required. please install it"
+    error "This program requires 'dig' to function. Please install it."
+    echo "'dig' is required. please install it."
     exit 1
 }
-
 
 #-------------------------------------------------------------------------------
 function _resolve2ip()
@@ -118,8 +149,8 @@ function _iterate_nameservers()
     }
 
     [[ ${#RESOLVED_IPS[@]} -gt 0 ]] || {
-    log "unable to connect to '${HOME_ADDR}'"
-    exit 1
+        log "unable to connect to '${HOME_ADDR}'. Aborting."
+        exit 1
     }
 
 }
@@ -142,7 +173,7 @@ for (( ip=0; ip < ${#RESOLVED_IPS[@]}; ip++ )); do
 done
 
 [[ ${RESOLVED_IP} ]] || {
-    log "unable to connect to '${HOME_ADDR}'"
+    log "unable to connect to '${HOME_ADDR}'. Aborting"
     exit 1
 }
 
@@ -188,6 +219,7 @@ done
         log "reverse tunnel to ${RESOLVED_IP} (${HOME_ADDR}) activated"
     } || {
         log "restarting reverse tunnel FAILED."
+        error "restarting reverse tunnel FAILED."
     }
 }
 #-------------------------------------------------------------------------------
@@ -252,30 +284,28 @@ Setup @ work
  @reboot             /path/to/revpipe 2>&1 >/dev/null
  */5  *  *   *   *   /path/to/revpipe 2>&1 >/dev/null
 
+
   youasroot@work~# crontab -e
 
  Use above command to edit root's crontab.
 
- The crontab above  will check the connection on reboot, and
- every 5 minutes thereafter while your work box is running.
- If the test fails 5 times, it will recreate the tunnel.
+ The crontab above will check the connection on reboot, and every 5
+ minutes thereafter while your work box is running.  If the connection
+ test fails 5 times during a cron cycle, it will recreate the tunnel.
 
 
 Advanced Work-side Configuration Options
 ---------------------------------------------------------------------
- If you want to use a faster but less secure cipher, such as arcfour
- or blowfish, you'll need to setup a Host section in your
+ If you want to use a faster but less secure tunnel cipher, such as
+ arcfour or blowfish, you'll need to setup a Host section in your
  ~/.ssh/config file. Create the file if it does not already exist.
 
  Example ~/.ssh/config Host section
 
-   Host *.yourdomain.com
+   Host <my.homepc.com OR my_home_ip_address>
        Ciphers arcfour,arcfour128,arcfour256,blowfish-cbc
        BatchMode yes
        Compression yes
-
- Then, set HOST=work-home-tunnel in the configuration
- section of revpipe
 
 
 Setup @ home
@@ -288,7 +318,7 @@ Setup @ home
  PermitRootLogin yes
 
  It's a VERY good idea, AFTER you have keys working from work to
- DISABLE password authentication in /etc/ssh/sshd_config on your
+ disable password authentication in /etc/ssh/sshd_config on your
  home desktop, as in:
 
  PasswordAuthentication no
@@ -314,22 +344,29 @@ Using the Tunnel
 
  NX server, from nomachine (www.nomachine.com), works great to deliver
  a full graphical desktop experience over this reverse tunnel. To use
- it, setup nxserver on your work box, and use nxclient on your home
+ it, setup nxserver on your work box and use nxclient on your home
  machine. In the client configuration, set your target to be
  localhost, on the port you specified above. I'm writing this on my
  work desktop from home. It spans two monitors fullscreen, and it
  feels almost as fast as being there. Try it - it blows vnc away.
 
 
+Other stuff
+---------------------------------------------------------------------
+
  Some other ssh settings to read up on:
   ServerAliveCountMax
   ServerAliveInterval
 
  Use 'apropos ssh' for a list of related ssh manpages. ssh_config is a
- good manpage to read.  If the tunnel is isolated by firewalls by IP
- addresses, you might consider a less robust tunnel cipher to improve
- performance, like possibly arcfour. Use root's ~/.ssh/config to
- modify the cipher for this connection only. See Advanced Work-side
- Configuration Options above for more information.
+ good manpage to read.  If the tunnel is isolated by your firewall by
+ IP addresses, you might consider a less robust tunnel cipher to
+ improve performance, like arcfour. Use root's ~/.ssh/config to modify
+ the cipher for this connection only.
+
+ See Advanced Work-side Configuration Options above for more
+ information. This cipher will only affect the tunnel, your sessions
+ back through the tunnel are still encrypted using your default
+ cipher.
 
 DOC
